project:
  type: website
  output-dir: docs/website




website:
  title: "passgen"
  repo-url: https://github.com/pedropark99/passgen
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/pages/how-to-build.qmd
        text: How to build
      - href: docs/pages/reference.qmd
        text: Documentation
    right:
      - icon: github
        href: https://github.com/pedropark99/passgen
      - icon: twitter
        href: https://twitter.com/PedroPark9
      - icon: envelope
        href: mailto:pedropark99@gmail.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



